---
- hosts: mywebservres
  become: yes
  tasks:
  - name: i want ot install java on ubuntu
    apt:
      name: "{{installjavaonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to install java on redhat
    yum:
      name: "{{installjavaonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"